'use client'
import { Inter, Oxygen, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

const oxygen = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-oxygen'
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-jakarta'
});


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en" suppressHydrationWarning="true">
    <head>
    <title>GPT Protocol</title>
    <meta name="description" content="hello" />
    <link rel="preload" href="/hero1.mp4" as="video" type="video/mp4" />
    <link rel="icon" href='/icon1.ico' sizes="16x16"/>
    </head>
      
      <body className={`${inter.variable} ${oxygen.variable} ${jakarta.variable}`}>
      <div className="data-scroll-container">
      <Header/>
      <div className="delay-scroll">
      {children}
      <Footer/>
      </div>
      </div>
      </body>
    </html>
  );
}
