'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {


  return (
    <html lang="en" suppressHydrationWarning="true">
    <head>
    <title>GPT Protocol</title>
    <meta name="description" content="hello" />
    <link rel="preload" href="/hero1.mp4" as="video" type="video/mp4" />
    <link rel="icon" href='/icon1.ico' sizes="16x16"/>
    </head>
      
      <body className={inter.className}>
      <div className="data-scroll-container">
      <Header/>
      <div className="delay-scroll">
      {children}
      <Footer/>
      </div>
      </div>
      </body>
    </html>
  );
}
